import './ShawshankRedemption.css';


function Descriptionpage2() {
    return(
    <div className='ShawshankRedemption'>
        
        
        <h1>The Shawshank Redemption </h1>
        <p>
        The Shawshank Redemption is a 1994 American prison drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. The film tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.

Darabont purchased the film rights to King's story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. Two weeks after submitting his script to Castle Rock Entertainment, Darabont secured a $25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place from June to August 1993 almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many stars for the role of Andy, including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film's score.

While The Shawshank Redemption received critical acclaim upon its release—particularly for its story, the performances of Robbins and Freeman, Newman's score, Darabont's direction and screenplay and Roger Deakins' cinematography—the film was a box-office disappointment, earning only $16 million during its initial theatrical run. Many reasons were cited for its failure at the time, including competition from the films Pulp Fiction and Forrest Gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. It went on to receive multiple award nominations, including seven Academy Award nominations, and a theatrical re-release that, combined with international takings, increased the film's box-office gross to $73.3 million.

Over 320,000 VHS rental copies were shipped throughout the United States, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. The broadcast rights were acquired following the purchase of Castle Rock by Turner Broadcasting System, and it was shown regularly on the TNT network starting in 1997, further increasing its popularity. Decades after its release, the film is still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most "beloved" films ever made. In 2015, the United States Library of Congress selected the film for preservation in the National Film Registry, finding it "culturally, historically, or aesthetically significant".

Plot
In early 1947, Portland, Maine, banker Andy Dufresne arrives at Shawshank State Prison to serve two consecutive life sentences for murdering his wife and her lover. He is befriended by Ellis "Red" Redding, a contraband smuggler serving a life sentence, who procures a rock hammer and a large poster of Rita Hayworth for Andy. Assigned to work in the prison laundry, Andy is frequently sexually assaulted by prison gang "the Sisters" and their leader, Bogs Diamond.

In 1949, Andy overhears the captain of the guards, Byron Hadley, complaining about being taxed on an inheritance and offers to help him shelter the money legally. After an assault by the Sisters nearly kills Andy, Hadley beats and cripples Bogs, who is subsequently transferred to another prison; Andy is not attacked again. Warden Samuel Norton meets Andy and reassigns him to the prison library to assist elderly inmate Brooks Hatlen, a front to use Andy's financial expertise to manage financial matters for other prison staff, guards from other prisons, and the warden himself. Andy begins writing weekly letters to the state legislature requesting funds to improve the prison's decrepit library.

Brooks is paroled in 1954 after serving 50 years, but he cannot adjust to the outside world and eventually hangs himself. The legislature sends a library donation that includes a recording of The Marriage of Figaro; Andy plays an excerpt over the public address system and is punished with solitary confinement. After his release from solitary, Andy explains to a dismissive Red that hope is what gets him through his sentence. In 1963, Norton begins exploiting prison labor for public works, profiting by undercutting skilled labor costs and receiving bribes. Andy launders the money using the alias "Randall Stephens".

In 1965, Andy and Red befriend Tommy Williams, a young prisoner incarcerated for burglary. A year later, Andy helps him pass his General Educational Development (GED) exam. Tommy reveals to Red and Andy that his cellmate at another prison had claimed responsibility for the murders of which Andy was convicted. Andy brings the information to Norton who refuses to listen and, when Andy mentions the money laundering, sends Andy to solitary confinement and has Hadley fatally shoot Tommy under the guise of an escape attempt. Andy refuses to continue the money laundering, but Norton threatens to destroy the library, remove Andy's protection by the guards, and move him to worse conditions. Andy is released from solitary confinement after two months, and he tells a skeptical Red that he dreams of living in Zihuatanejo, a Mexican town on the Pacific coast. Andy also tells him of a specific hayfield near Buxton, asking Red to promise, once he is released, to retrieve a package that Andy buried there. Red worries about Andy's mental well-being, especially when he learns Andy asked a fellow inmate for some rope.

At the next day's roll call, the guards find Andy's cell empty. An irate Norton throws a rock at a poster of Raquel Welch hanging on the cell wall, revealing a tunnel that Andy had dug with his rock hammer over nearly two decades. The previous night, Andy used the rope to escape through the tunnel and prison sewage pipe, taking Norton's suit, shoes, and ledger, containing evidence of the money laundering. While guards search for him, Andy poses as Randall Stephens, withdraws over $370,000[a] of the laundered money from several banks, and mails the ledger and other evidence of the corruption and murders at Shawshank to a local newspaper. State police arrive at Shawshank and take Hadley into custody, while Norton commits suicide to avoid arrest.

The following year, Red is paroled after serving 40 years but struggles to adapt to life outside prison and fears that he never will. Remembering his promise to Andy, he visits Buxton and finds a cache containing money and a letter asking him to come to Zihuatanejo. Red violates his parole by traveling to Fort Hancock, Texas, and crossing the border into Mexico, admitting that he finally feels hope. He finds Andy sanding an old boat on a Zihuatanejo beach, and the two reunited friends happily embrace.
        </p>
        <div>
            <button onClick={() => {window.location.href= "./"}}>back</button>
        </div>
    </div>
    );
}

export default Descriptionpage2